//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfClinic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmin
    {
        public int AdminID { get; set; }
        public int AccountID { get; set; }
        public Nullable<bool> LoggedIn { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
    }
}
