//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfClinic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClinic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblClinic()
        {
            this.tblAccounts = new HashSet<tblAccount>();
        }
    
        public int ClinicID { get; set; }
        public string ClinicName { get; set; }
        public System.DateTime OpenDate { get; set; }
        public int OwnerID { get; set; }
        public string Adress { get; set; }
        public Nullable<int> NumberOfFloors { get; set; }
        public Nullable<int> RoomsByFloor { get; set; }
        public Nullable<int> OfficeNumber { get; set; }
        public Nullable<bool> Balcony { get; set; }
        public Nullable<bool> Yard { get; set; }
        public Nullable<int> NumberOfAmbulanceCarParkings { get; set; }
        public Nullable<int> NumberOfInvalidEntrances { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccount> tblAccounts { get; set; }
        public virtual tblOwner tblOwner { get; set; }
    }
}
