//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfClinic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDoctor()
        {
            this.tblPatients = new HashSet<tblPatient>();
        }
    
        public string DoctorNumber { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string BankAccount { get; set; }
        public string Department { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<bool> PatientReception { get; set; }
        public Nullable<int> ManagerID { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblManager tblManager { get; set; }
        public virtual tblShift tblShift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPatient> tblPatients { get; set; }
    }
}
